;; Generated by :claw at 2021-06-12T21:15:19.056244+03:00
(asdf:defsystem #:bodge-libc-essentials-bindings
  :description "Bindings generated by bodge-libc-essentials/wrapper"
  :author "CLAW"
  :license "Public domain"
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi)
  :components
  ((:file
    "/home/borodust/devel/repo/bodge-projects/bodge-libc-essentials/x86_64-pc-linux-gnu"
    :if-feature (:and :x86-64 :linux))
   (:file
    "/home/borodust/devel/repo/bodge-projects/bodge-libc-essentials/i686-pc-linux-gnu"
    :if-feature (:and :x86 :linux))
   (:file
    "/home/borodust/devel/repo/bodge-projects/bodge-libc-essentials/x86_64-pc-windows-gnu"
    :if-feature (:and :x86-64 :windows))
   (:file
    "/home/borodust/devel/repo/bodge-projects/bodge-libc-essentials/i686-pc-windows-gnu"
    :if-feature (:and :x86 :windows))
   (:file
    "/home/borodust/devel/repo/bodge-projects/bodge-libc-essentials/x86_64-apple-darwin-gnu"
    :if-feature (:and :x86-64 :drawin))
   (:file
    "/home/borodust/devel/repo/bodge-projects/bodge-libc-essentials/i686-apple-darwin-gnu"
    :if-feature (:and :x86 :drawin))))